### ISSUE TITLE
val_acc error

### ISSUE THREAD

**Issue by nubonics** [DaiCapra/Natural-Mouse-Movements-Neural-Networks#1]
python3.7 main_path.py
Using TensorFlow backend.
2020-05-24 10:46:51.949622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-24 10:46:51.977264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:51.978080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.86GHz coreCount: 14 deviceMemorySize: 3.81GiB deviceMemoryBandwidth: 119.24GiB/s
2020-05-24 10:46:51.978264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-24 10:46:51.979267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-24 10:46:51.980501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-24 10:46:51.980684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-24 10:46:51.981722: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-24 10:46:51.982196: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-24 10:46:51.984400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-24 10:46:51.984513: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:51.984834: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:51.985087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-24 10:46:51.985336: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-24 10:46:52.012351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600030000 Hz
2020-05-24 10:46:52.012836: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7efadc000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-24 10:46:52.012865: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-24 10:46:52.176158: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.176517: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56555ad18a10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-24 10:46:52.176540: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1650, Compute Capability 7.5
2020-05-24 10:46:52.176731: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.177115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.86GHz coreCount: 14 deviceMemorySize: 3.81GiB deviceMemoryBandwidth: 119.24GiB/s
2020-05-24 10:46:52.177179: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-24 10:46:52.177200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-24 10:46:52.177219: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-24 10:46:52.177237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-24 10:46:52.177255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-24 10:46:52.177273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-24 10:46:52.177291: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-24 10:46:52.177356: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.177760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.178219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-24 10:46:52.178259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-24 10:46:52.178789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-24 10:46:52.178804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-05-24 10:46:52.178812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-05-24 10:46:52.178931: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.179338: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-24 10:46:52.179714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2255 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:2d:00.0, compute capability: 7.5)
Train on 20346 samples, validate on 1071 samples
Epoch 1/1000
2020-05-24 10:46:52.840229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
   32/20346 [..............................] - ETA: 2:34 - loss: 45284.4805 - mean_squared_error: 45284.4805 - accuracy: 0.45  992/20346 [>.............................] - ETA: 5s - loss: 19887.5697 - mean_squared_error: 19887.5703 - accuracy: 0.949420346/20346 [==============================] - 1s 70us/step - loss: 10088.8819 - mean_squared_error: 10088.8818 - accuracy: 0.9930 - val_loss: 3886.5988 - val_mean_squared_error: 3886.5986 - val_accuracy: 0.9961
Traceback (most recent call last):
  File "main_path.py", line 17, in <module>
    history = model.fit(train_inputs, train_paths, epochs=1000, verbose=1, validation_split=0.05, callbacks=callbacks_list)
  File "/home/nubonix/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/home/nubonix/.local/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 216, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/nubonix/.local/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/nubonix/.local/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 702, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_acc'

**Comment by nubonics** [comment]
Changing val_acc to val_accuracy in main_*.py AND
By removing the callback to the checkpoints, as it attempts to use the checkpoints compiled in an earlier tensorflow/keras version.
I am using tensorflow 2.2.0

Solved
